---
title: "Proposal Checklist"
---

## The 13 Things We're Looking for

1.	The complete proposal is submitted on time.
    - On time for the initial submission means R Markdown and HTML on Canvas by 2020-10-02 at Noon. If it's late, it will be reviewed last, and severely penalized.
    - If you worked with a partner, both names are on the documents submitted by one of you, while the other submitted a note to Canvas meeting the specifications described in the Project A instructions.
    - When we run the R Markdown file, does it produce the HTML file without errors? (Note: warnings or messages are OK at this stage, but it has to work.)
    
2.	The YAML in the R Markdown file produces what we want in the HTML
    - There's a real title that does not include Project A or Proposal and that is correctly spelled, and fits in the available space in the HTML.
    - The author(s) name appears in the HTML correctly.
    - The date is properly formatted in the HTML (achieve this most easily by using the **r Sys.Date()** command within the date section of the YAML as Dr. Love does in his work.)
    - There is a table of contents (doesn’t have to float, although we prefer this) which appears in the HTML and has section names that are appropriately and automatically numbered.
        - To achieve this, use **number_sections: TRUE** in the YAML.
    - The easiest approach to accomplish all of this is to use the readthedown template as Dr. Love did in the Example.
    
3.	The project ingests the data properly.
    - Eliminating the correct row (in any way that works), and 
    - Using `read_csv()` to read in the data, thus creating a tibble

4.	All section headings are correctly numbered and formatted, and describe effectively the contents of the material contained in that section.
    - Reusing Dr. Love’s headings from the example proposal is a good option, but it's OK if you want to take a different approach, so long as we can find everything.
    - Again, you need to be using `toc: TRUE` and `number_sections: TRUE` in your YAML if you are building an html_document and not using the readthedown template that Dr. Love used in his example.
    - If you’re using the readthedown template, then you need number_sections: TRUE, but **not** toc:TRUE since that will be done automatically by the readthedown template.


5.	You have an attractively formatted, readable codebook that looks nice in your HTML.
    - The example proposal provides an example, but you can come up with something better if you like. It must be run within R Markdown though - you cannot submit an image instead of getting the codebook through code.

6.	Which states were chosen is clear, and there is a sentence about why they were chosen.
    - There must be 4-6 states, including Ohio
    - This must lead to 200-400 counties, and this number must be clear from the document (both the number of rows in the final tibble and in writing.)
    - You should not drop any counties from any of the states you selected in the development of your tibble.
    
7.	Your selected five variables are clear, and there is information about what the variables mean and why you chose them, and the role they will play in your eventual analyses
    - You clearly specify which of your 5 variables is the outcome
    - You clearly specify which variable will be treated as a binary categorical variable, and which will be treated as a multi-categorical variable, specifying how many categories will be used, and why you made the choices you did about splitting those variables into categories.
    - For each of your quantitative variables (outcome and the two predictors) you specify their units in appropriate language drawn from the measure specifications at County Health Rankings.
    - You specify all variables using the name you will use in your final tibble, the `vXXX` code from the original data, and show that you have some understanding of what the variable means, how it was collected and why it is important in your sentences surrounding your codebook.

8.	The results of your missingness check and your # of distinct values check are clear, and meet the specifications described in the instructions. 
    - You've written a sentence (at least) in response to the results of each check that makes sense.

9.	You've printed your final tibble by typing in its name, and it appears as a tibble.

10.	`Hmisc::describe` results for your final set of 10 variables, with minimum and maximum values that make sense, and that show the correct number of counties and states.

11.	Your response to question 5 is a paragraph (or more) written in English, with attention paid to grammar, syntax and spelling. 
    - It is clear to us what your biggest issue was, and how you tried to address it.
    
12.	There is a Session Information section at the end of the document.
    - We would prefer that this indicates that R version 4.0.2 is used, but we don’t require that for Project A, so long as you're using version 3.6.1 or later.
    
13.	You don’t have more than 3 spelling, typographical or grammatical errors in the document as a whole that we catch.

## Grading Clarification

Dr. Love and the TAs will review your proposal and either ACCEPT it or ask for a REDO.

- ACCEPT means you're done, and should move on the rest of Project A, perhaps while making some small changes that we request of you in your submission on Canvas.
- REDO means you'll need to fix the problems we’ve identified (plus make sure you've done all of the things on this checklist) and resubmit by the deadline we give you.
    - If your proposal is accepted on the initial submission, you'll receive 25 points.
    - If your proposal is accepted on the first REDO (submission 2), you'll receive 22.5 points.
    - If your proposal is accepted on the second REDO (submission 3), you'll receive 20 points.
    - We hope we won’t have to go further than 3 attempts for anyone.

If you don’t have some feature that we "prefer" we may mention this and ask you to fix it in the final version of the complete Project A, but that alone wouldn't necessitate a REDO.

