---
title: "Project A Data"
---

This page was last updated: `r Sys.time()`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# What Data Will I Use?

The data set for Project A is now available. The data are the 2020 version of the analytic data from County Health Rankings. In much of what follows, we will abbreviate County Health Rankings as CHR.

The data are gathered at [the County Health Rankings Data & Documentation site](https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation).

The key links for you are provided as part of the National Data & Documentation section of that site for the **2020 County Health Rankings**. Do not use data from previous editions of the CHR, and do not use the trends data in this project. 

Specifically, you'll need three files:

- [the 2020 CHR CSV Analytic Data](https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2020_0.csv) (a .csv file)
- [the 2020 CHR Analytic Data Documentation](https://www.countyhealthrankings.org/sites/default/files/media/document/2020%20Analytic%20Documentation_0.pdf) file (PDF), and
- [the 2020 Data Dictionary](https://www.countyhealthrankings.org/sites/default/files/media/document/DataDictionary_2020_2.pdf) (PDF)

These files are also available in the [data folder for Project A](https://github.com/THOMASELOVE/431-2020/blob/master/projects/projectA/data/README.md) on Github, and in the Google Drive folder Dr. Love has shared with you. 

# Cleaning the Data

Cleaning the data will be a time-consuming effort but you can begin it immediately. Before you complete any of the required analyses in R, you'll need to complete the following steps.

1. Remove the first row of the csv file to leave the second row as the top row before ingesting the data into R (I suggest you do this in Excel or perhaps Google Sheets, and then resave a new version of the file without this top row as a .csv before ingesting into R)
2. Select variables (there will be 3 required variables, plus 5 additional variables you select, for a total of 8) that you actually need to use and rename them into useful formats instead of the default names provided by CHR.
3. Filter to the subset of observations (counties) that you actually want to study, and note that each of these counties will have to have a `county_ranked` value of 1, and in addition, you will be working with a subset of the available `state`s, which should include the 88 counties of Ohio, plus counties from 3-5 other states you will select. 
4. Make some transformations to obtain categorical versions (factors) of selected variables and add them to your tibble.

# Data Development Task List

1. **Identify a set of 4-6 states, containing 200-400 counties.** This must include the 88 counties of Ohio, and all of the counties within a subset of 3-5 additional states in the US, not including the District of Columbia, and also not including the five states (Connecticut, Delaware, Hawaii, New Hampshire and Rhode Island) with fewer than 12 counties. The number of counties associated with each state (specified using its two-letter postal abbreviation code) is listed below, for your convenience.

## States with fewer than 12 counties are italicized below.

`state` | Name | Counties | |  `state` | Name | Counties 
:---: | ----: | ---: | --: |  :---: | ---: | ----: 
`AK` | Alaska | 25 |  | `AL` | Alabama | 67
`AR` | Arkansas | 75 |  | `AZ` | Arizona | 15
`CA` | California | 58 |  | `CO` | Colorado | 60
`CT` | *Connecticut* | *8* |  | `DE` | *Delaware* | *3*
`FL` | Florida | 67 |  | `GA` | Georgia | 159
`HI` | *Hawaii* | *4* |  | `IA` | Iowa | 99
`ID` | Idaho | 42 |  | `IL` | Illinois | 102
`IN` | Indiana | 92 |  | `KS` | Kansas | 104
`KY` | Kentucky | 120 |  | `LA` | Louisiana | 64
`MA` | Massachusetts | 14 |  | `MD` | Maryland | 24
`ME` | Maine | 16 |  | `MI` | Michigan | 83
`MN` | Minnesota | 87 |  | `MO` | Missouri | 115
`MS` | Mississippi | 82 |  | `MT` | Montana | 48
`NC` | North Carolina | 100 |  | `ND` | North Dakota | 48
`NE` | Nebraska | 80 |  | `NH` | *New Hampshire* | *10*
`NJ` | New Jersey | 21 |  | `NM` | New Mexico | 32
`NV` | Nevada | 15 |  | `NY` | New York | 62
`OH` | Ohio | 88 |  | `OK` | Oklahoma | 77
`OR` | Oregon | 35 |  | `PA` | Pennsylvania | 67
`RI` | *Rhode Island* | *5* |  | `SC` | South Carolina | 46
`SD` | South Dakota | 61 |  | `TN` | Tennessee | 95
`TX` | Texas | 244 |  | `UT` | Utah | 28
`VA` | Virginia | 133 | | `VT` | Vermont | 14
`WA` | Washington | 39 | | `WI` | Wisconsin | 72
`WV` | West Virginia | 55 | | `WY` | Wyoming | 23

So, including `OH`, you will need a total of 200-400 counties, from 4-6 states. For example,

- one possible combination would be the states of `TX` (244 counties), `AZ` (15 counties) and `NM` (32 counties) in addition to `OH` (88 counties), which would yield 379 counties in 4 states
- another combination would be the states of `WA` (39 counties), `WI` (72 counties), `WV` (55 counties) and `WY` (23 counties) to join `OH` (88 counties) yielding 277 counties in 5 states
- and yet another would be `PA` (67), `NY` (62), `NJ` (21), `MD` (24) and `VA` (133) in addition to `OH` (88) yielding 395 counties in 6 states

**Note 1**: You can choose your subset of states in any way you like, keeping in mind that some variables in the CHR data are not available for some counties, and that each state you select should have more than 12 counties. You should have some reason for selecting the states that you do, and you should describe that reason in a complete sentence or two in your report.

2. **Identify Your Variables**: Identify variables from the data for your selected sample of counties that will allow you to develop a data set that includes:

- the five-digit fips code for the county, which will be a convenient ID variable
- the name of the county, which will be useful for labeling and identifying the counties 
- the `state`, which will be a multi-categorical (with 4-6 categories) variable
- and a total of five variables selected from the 107 variables in the CHR data set that are listed as `vXXX_rawvalue` (note: to select the entire group of 107 variables, you might try `select(ends_with("rawvalue"))` as part of a pipe of the data.)

**Note 2**: Each of the five variables you select must have data for at least 75% of the counties in each state you plan to study. This is something you will have to check on.

**Note 3**: Across your complete set of 4-6 selected states, the raw versions of each of your five selected variables must have at least 10 distinct non-missing values. Again, you'll need to show that you have checked this to be true.

3. **Create Modified Variables**: Create your actual variables. Your five selected quantitative variables, selected by you from the 107 available "raw value" CHR variables, will need be treated as follows:

- variable 1 will be treated as quantitative, and as an outcome of interest
- two others (variables 2 and 3) will also be treated as quantitative predictors of interest for variable 1
- variable 4 will be categorized into 2 mutually exclusive and collectively exhaustive levels to create a binary categorical variable of interest in predicting variable 1
- variable 5 will be categorized into 3-5 mutually exclusive and collectively exhaustive levels to create a multi-categorical variable of interest in predicting variable 1
- the `state` will serve as another multi-categorical (with 4-6 categories) predictor of variable 1, so this will also be part of your tibble

4. **Create your Main Tibble**: Your main data set for analysis then should be gathered into a tibble containing the following information:

- the identifying variables for each county, specifically:
    - `fipscode` = the five-digit fips code for the state and county,
    - `county` = the name of the county
    - `state` = the postal abbreviation code for the state
- renamed versions of the original "raw value" versions of the five variables you've chosen, renamed to be more descriptive, and appended with `_raw` so that, for example, if you choose to use variable `v009_rawvalue` which is about adult smoking, your variable name should be `adult_smoking_raw`
- your six "clean" versions of the data as described above, with your variables 2, 5 and 6 categorized appropriately using R code, and all of them renamed to be useful, so, for instance, if you've categorized the adult smoking variable, you might name that `adult_smoking_cat`, and if you've treated it as quantitative, you might name it `adult_smoking`.

Each row in this tibble should contain all of the counties within the 4-6 states you are studying, and no other counties should be included in your tibble. If data for some counties are missing in the raw data for one or more of your variables, then these data should be indicated as missing (using NA) in the tibble.

In your R Markdown file, you will need to present all code necessary to take the original .csv data file (with the top row removed outside of R) and wind up with this tibble.

## Evaluating Your Tibble Numerically

You will then prove that your tibble is in fact a tibble and not just a data frame by listing it, so that the first 10 rows are printed, and the columns are appropriately labeled.

You will then provide a codebook as a table in your R Markdown file (and HTML/PDF output) that specifies the name of each variable in your tibble and its definition.

You will then demonstrate main numerical summaries from the tibble by running the following three summaries:

1. `Hmisc::describe` on the whole data set
2. `mosaic::favstats` on each of your final (not raw) versions of the quantitative variables (so variables 1, 2, and 3)
3. `janitor::tabyl` on your categorical variables 4 and 5 as well as on `state`.


