---
title: "Examples"
---

This page was last updated: `r Sys.time()`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

Dr. Love has prepared the following materials to help you with your project A work:

## Our Advice

The most important recommendation we have is to use the proposal example R Markdown file Dr. Love has prepared (described in Item 2 below) as a starting point for your own data and proposal development. In combination with the video (Item 1) linked below, this should provide a powerful set of tools for you to complete the Proposal successfully on your first submission.

### Item 1: 30-Minute Video to Get Started

On 2020-09-17, Dr. Love built a 30-minute video recording walking through the first steps in setting up the data for your project A in R.

In this video, you will see Dr. Love:

- download the .csv and .pdf files from the Project A web site to a folder on his computer
- remove the first row of the .csv using Excel (and also using Google Sheets if you prefer that approach), then 
- create a project in R Studio for Project A associated with the folder where he downloaded the materials from the web,
- set up an R Markdown file to do the work,
- read the data into a tibble in R, first in a simple way that doesn't quite work, and then again more correctly (so that all 107 of the variables you can choose from are interpreted properly by R as double-precision numeric variables), then
- walk through the process of using `filter` and `select` to identify the right counties, and select the states and variables you want to study further,
- and this includes looking up and renaming one of the variables you might select, both within the PDF files, and when that proves insufficient, visiting the County Health Rankings website to get the information you'll need to describe the variables properly for the project.

To watch the video, you have two options:

1. Visit the **431 Fall 2020 Dr Love and Students** Shared Drive in Google, which you should be able to get to when you are logged into Google via CWRU. The recording is found in the "Dr Love Special Videos" folder under the filename "Dr_Love_sets_up_project_A_2020-09-17.mp4".

2. Visit the "Files" section of Canvas for the course, and look for the recording which, again, is called "Dr_Love_sets_up_project_A_2020-09-17.mp4".

Let us know if you have any trouble watching the video.

### Item 2: Project Proposal Example using 2019 Data

Dr. Love has completed an R Markdown file and compiled it into an HTML result which you can view now, and which he **strongly** encourages you to use in developing your own proposal.

All of the files are downloadable now, in [our Github repository](https://github.com/THOMASELOVE/431-2020/tree/master/projects/projectA/example_projectA_proposal) for this proposal example.

If you prefer, you can visit the **431 Fall 2020 Dr Love and Students** Shared Drive in Google, which you should be able to get to when you are logged into Google via CWRU. The recording is found in the "Examples for Project A" subfolder, which includes a folder of data, in addition to the R Markdown and HTML files.

The files associated with this example include:

- Dr. Love's R Markdown file
- Dr. Love's resulting HTML file, which you can download at the links above, and also view directly at https://rpubs.com/TELOVE/projA-proposal-example-431-2020.
- data (.csv) as downloaded from County Health Rankings for **2019**
- the raw data (also .csv) after removing the top row of the downloaded file
- two PDFs from County Health Rankings identifying the variables in the data

### Additional items

Coming in October.
