---
title: "431 Project A Instructions"
---

This page was last updated: `r Sys.time()`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

## Your Final Submission involves Three Parts

1. **The Report** You will submit a polished report in both R Markdown and either HTML or PDF addressing all of the issues described in the Data Development and Analytic Tasks.

2. **The Video** You will produce a video in the mp4 format of no more than 3 minutes in length if you're working alone, and of no more than 5 minutes in length between you if you are working in a pair. In this video, you will describe what you believe to be the most important findings for your choice of two of the four analyses you will complete. 
    - If you are working in a pair, each of you will present one of the two analyses. 
    - Your video must include your face (so recording in Zoom is preferable) and must share graphs and results taken from the report you build. 
    - The video must stand on its own, in the sense that it must be completely understandable to someone who has not read your report, but who is generally familiar with County Health Rankings and its measurements.

3. **The Self-Evaluation** You will each (whether working alone or with a partner) submit a brief self-evaluation via a Google Form Dr. Love will make available in October. The form should take about 10 minutes to complete.

All three elements are due on 2020-10-20 at Noon.

### Grading

- Project A is graded on a scale from 0 to 100, although I expect the highest grade to be close to 95. Dr. Love works with the TAs to provide feedback and grade the projects, but the final Project A grade is determined solely by him.
    - As we've seen previously, the Proposal is worth (up to) 25 points. Many students will score 25 points, and we expect most students to score at least 20.
- The Report is worth 40 points. It is unlikely that anyone will score above 37 points, which is the planned score for a completely accurate and polished report. Most scores will likely fall between 25 and 35 points on this element. 
- The Video is worth 25 points. It is unlikely that anyone will score above 23 points, which is the planned score for a very strong presentation, which is clear to see and hear and which is effective. Most scores will likely fall between 16 and 22 points on this element.
- The Self-Evaluation is worth 10 points. Most people who complete the self-evaluation thoughtfully will receive the full 10 points.

Overall, a project score of 85 or higher is regarded as an A, and a score of 70 to 84 is regarded as a B. Project grading is set up to generate a median score near 84.


