---
title: "Project A Proposal"
---

This page was last updated: `r Sys.time()`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# Your "Proposal" will be due 2020-10-02 at Noon

You will submit a short document to Canvas providing the answers to a series of questions related to your Data Development work. The TAs and Dr. Love will review these results to ensure that your proposed plan meets the requirements for this project, and either approve the plan, or request changes. If changes are requested, you'll have 48 hours to make those changes and resubmit until your plan is approved. 

## Working Alone vs. Working in a Group

You may work alone on this project, or in a group of two people. If you decide to work in a pair, you will specify that in the "proposal" stage, and you're stuck with that choice for the rest of Project A.

# Your Project "Proposal" due 2020-10-02 at noon

Your project proposal requires you to create the tibble you plan to use and then send (via Canvas) an R Markdown file and HTML (or PDF) result that contains:

1. A list of the states you chose, and the number of counties you are therefore studying.
2. A list of the five variables (including their original raw names and your renamed versions) you are studying, with a clear indication of how you're planning to create the categories in variables 4 and 5.
3. A print-out of your tibble, to prove it is a tibble.
4. The `Hmisc::describe` result for your tibble

Be sure that your proposal includes your name as the author in R Markdown.

Dr. Love will provide an R Markdown template for the project "proposal" document to you.

## Working with a partner?

Be sure that your proposal includes your name and that of your partner (if you have one.) If you are working with a partner, exactly one of you should submit the materials, and the other partner should submit a text document (Word or PDF is fine) that reads 

"My name is [YOUR NAME]. I am working on Project A with [INSERT FULL NAME OF YOUR PARTNER], and they will submit the materials for the proposal."